// <auto-generated />
namespace MyFinance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DateTime2ConventionMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTime2ConventionMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201904191421538_DateTime2ConventionMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
